#ifndef GUARD_CONSTANTS_POKEMON_VENDOR_H
#define GUARD_CONSTANTS_POKEMON_VENDOR_H

#define POKEMON_VENDOR_NO_PRODUCT_ID 0
#define POKEMON_VENDOR_NO_FLAG 0
#define POKEMON_VENDOR_DEFAULT_BOND_THRESHOLD 100

#define POKEMON_VENDOR_PRODUCT_NORMAL 0
#define POKEMON_VENDOR_PRODUCT_SEALED 1

#define POKEMON_VENDOR_PURCHASE_REPEAT 0
#define POKEMON_VENDOR_PURCHASE_ONCE 1

#define POKEMON_VENDOR_EDIT_NORMAL 0
#define POKEMON_VENDOR_EDIT_ALWAYS 1

#define POKEMON_VENDOR_REVEAL_SPECIES 0
#define POKEMON_VENDOR_REVEAL_LOCKED 1

#endif // GUARD_CONSTANTS_POKEMON_VENDOR_H
