#ifndef GUARD_CONSTANTS_SCOUT_SELECTION_H
#define GUARD_CONSTANTS_SCOUT_SELECTION_H

#define SCOUT_POOL_STARTER_TEST 0

#define SCOUT_RESULT_CANCEL   0
#define SCOUT_RESULT_SELECTED 1

#endif // GUARD_CONSTANTS_SCOUT_SELECTION_H
