#!/usr/bin/env python3

import json
import sys
from pathlib import Path


MAX_CANDIDATES = 12
POOL_NAME = "sPartygenDemoMons"
# partygen JSON stores HP/Atk/Def/SpA/SpD/Spe. MON_DATA_* order is
# HP/Atk/Def/Spe/SpA/SpD, so generated C arrays are converted here.
RUNTIME_STAT_ORDER_FROM_PARTYGEN = [0, 1, 2, 5, 3, 4]


def fail(message):
    raise SystemExit(f"make_scout_pools.py: {message}")


def validate_constant(value, prefix, set_id, field):
    if not isinstance(value, str) or not value.startswith(prefix):
        fail(f"{set_id} has invalid {field}: {value}")
    return value


def parse_level(raw, set_id):
    try:
        level = int(raw)
    except ValueError:
        fail(f"{set_id} has non-numeric level: {raw}")
    if level < 1 or level > 100:
        fail(f"{set_id} has out-of-range level: {raw}")
    return level


def parse_stats(raw, set_id, field, max_value):
    parts = raw.split("/")
    if len(parts) != 6:
        fail(f"{set_id} has invalid {field}: {raw}")
    try:
        values = [int(part) for part in parts]
    except ValueError:
        fail(f"{set_id} has non-numeric {field}: {raw}")
    for value in values:
        if value < 0 or value > max_value:
            fail(f"{set_id} has out-of-range {field}: {raw}")
    if field == "evs" and sum(values) > 510:
        fail(f"{set_id} has EV total above 510: {raw}")
    return [values[i] for i in RUNTIME_STAT_ORDER_FROM_PARTYGEN]


def padded_moves(raw_moves, set_id):
    if not raw_moves:
        return ["MOVE_DEFAULT"] * 4
    if len(raw_moves) > 4:
        fail(f"{set_id} has more than 4 moves")
    moves = [validate_constant(move, "MOVE_", set_id, "move") for move in raw_moves]
    while len(moves) < 4:
        moves.append("MOVE_NONE")
    return moves


def collect_sets(paths):
    selected = []
    seen_species = set()

    for path in paths:
        data = json.loads(path.read_text(encoding="utf-8"))
        if data.get("schemaVersion") != 1:
            fail(f"{path} has unsupported schemaVersion: {data.get('schemaVersion')}")
        for entry in data.get("sets", []):
            set_id = entry.get("id", str(path))
            species = entry.get("species")
            if not species:
                fail(f"{set_id} has no species")
            species = validate_constant(species, "SPECIES_", set_id, "species")
            if species in seen_species:
                continue

            selected.append(
                {
                    "id": set_id,
                    "species": species,
                    "level": parse_level(entry.get("level", 50), set_id),
                    "item": validate_constant(entry.get("item") or "ITEM_NONE", "ITEM_", set_id, "item"),
                    "ball": validate_constant(entry.get("ball") or "BALL_POKE", "BALL_", set_id, "ball"),
                    "nature": validate_constant(entry.get("nature") or "NATURE_RANDOM", "NATURE_", set_id, "nature"),
                    "ability": validate_constant(entry.get("ability") or "ABILITY_NONE", "ABILITY_", set_id, "ability"),
                    "moves": padded_moves(entry.get("moves"), set_id),
                    "ivs": parse_stats(entry.get("ivs", "31/31/31/31/31/31"), set_id, "ivs", 31),
                    "evs": parse_stats(entry.get("evs", "0/0/0/0/0/0"), set_id, "evs", 255),
                }
            )
            seen_species.add(species)

            if len(selected) == MAX_CANDIDATES:
                return selected

    return selected


def c_array(values):
    return "{ " + ", ".join(str(value) for value in values) + " }"


def emit(output, inputs, sets):
    if len(sets) < MAX_CANDIDATES:
        fail(f"expected at least {MAX_CANDIDATES} unique species, found {len(sets)}")

    rel_inputs = ", ".join(str(path) for path in inputs)
    lines = [
        "// DO NOT MODIFY THIS FILE! It is auto-generated by tools/scout_selection/make_scout_pools.py.",
        f"// Source JSON: {rel_inputs}",
        "// Deduplication: first set per species wins; first 12 unique species are emitted.",
        "",
        f"static const struct ScoutMonSpec {POOL_NAME}[] =",
        "{",
    ]

    for entry in sets:
        moves = "{ " + ", ".join(entry["moves"]) + " }"
        lines.append(f"    // {entry['id']}")
        lines.append(
            "    { "
            f"{entry['species']}, {entry['level']}, {entry['item']}, {entry['ball']}, "
            f"{entry['nature']}, {entry['ability']}, MON_GENDER_RANDOM, {moves}, "
            f"{c_array(entry['ivs'])}, {c_array(entry['evs'])} "
            "},"
        )

    lines.extend(
        [
            "};",
            "",
            "static const struct ScoutPool sScoutPools[] =",
            "{",
            f"    [SCOUT_POOL_PARTYGEN_DEMO] = {{ {POOL_NAME}, ARRAY_COUNT({POOL_NAME}) }},",
            "};",
            "",
        ]
    )
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines), encoding="utf-8")


def main():
    if len(sys.argv) < 3:
        fail("usage: make_scout_pools.py OUTPUT INPUT_JSON...")

    output = Path(sys.argv[1])
    inputs = [Path(arg) for arg in sys.argv[2:]]
    sets = collect_sets(inputs)
    emit(output, inputs, sets)


if __name__ == "__main__":
    main()
