#include "global.h"
#include "battle.h"
#include "test/battle.h"
#include "battle_ai_util.h"

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY: AI conserves Dynamax when it has no immediate payoff")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { HP(300); Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_SCRATCH, gimmick: GIMMICK_NONE); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY: AI can spend Dynamax on its last Pokemon")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_SCRATCH, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY: AI can spend Dynamax with one reserve when low on HP")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(50); MaxHP(100); Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_SCRATCH, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY: AI can spend Dynamax to set rain with Max Geyser")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_WATER_GUN); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_WATER_GUN, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY: AI can spend Dynamax to block Fake Out disruption")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_FAKE_OUT) == EFFECT_FIRST_TURN_ONLY);
        ASSUME(MoveHasAdditionalEffect(MOVE_FAKE_OUT, MOVE_EFFECT_FLINCH));
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(100); Moves(MOVE_FAKE_OUT); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { MOVE(player, MOVE_FAKE_OUT); EXPECT_MOVE(opponent, MOVE_SCRATCH, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_READ_PLAYER_MOVE: AI can spend Dynamax against an already chosen Fake Out")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_FAKE_OUT) == EFFECT_FIRST_TURN_ONLY);
        ASSUME(MoveHasAdditionalEffect(MOVE_FAKE_OUT, MOVE_EFFECT_FLINCH));
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY | AI_FLAG_READ_PLAYER_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(100); Moves(MOVE_FAKE_OUT); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { MOVE(player, MOVE_FAKE_OUT); EXPECT_MOVE(opponent, MOVE_SCRATCH, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_DOUBLE_BATTLE_TEST("AI_FLAG_READ_PLAYER_MOVE: AI scores against selected player Tera type")
{
    GIVEN {
        ASSUME(GetMoveType(MOVE_DRAGON_CLAW) == TYPE_DRAGON);
        ASSUME(GetMoveType(MOVE_COLLISION_COURSE) == TYPE_FIGHTING);
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_READ_PLAYER_MOVE);
        PLAYER(SPECIES_MIRAIDON) { HP(500); Speed(120); TeraType(TYPE_ELECTRIC); Moves(MOVE_DRACO_METEOR); }
        PLAYER(SPECIES_LUNALA) { HP(500); Speed(200); Moves(MOVE_TAILWIND); }
        OPPONENT(SPECIES_KORAIDON) { Attack(200); Speed(100); Moves(MOVE_COLLISION_COURSE, MOVE_DRAGON_CLAW); }
        OPPONENT(SPECIES_MIRAIDON) { Speed(100); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN {
            MOVE(playerLeft, MOVE_DRACO_METEOR, target: opponentRight, gimmick: GIMMICK_TERA);
            MOVE(playerRight, MOVE_TAILWIND);
            EXPECT_MOVE(opponentLeft, MOVE_COLLISION_COURSE, target: playerLeft);
        }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_READ_PLAYER_MOVE: AI scores against the actual selected switch-in")
{
    GIVEN {
        ASSUME(GetMoveType(MOVE_THUNDERBOLT) == TYPE_ELECTRIC);
        ASSUME(GetMoveType(MOVE_SURF) == TYPE_WATER);
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_PREDICTION | AI_FLAG_READ_PLAYER_MOVE);
        PLAYER(SPECIES_GYARADOS) { HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_DUGTRIO) { HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { SpAttack(200); Speed(50); Moves(MOVE_THUNDERBOLT, MOVE_SURF); }
    } WHEN {
        TURN {
            SWITCH(player, 1);
            EXPECT_MOVE(opponent, MOVE_SURF);
        }
    }
}

AI_DOUBLE_BATTLE_TEST("AI_FLAG_READ_PLAYER_MOVE: command log records all double battle choices")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_READ_PLAYER_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT) { HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_SCRATCH); }
        OPPONENT(SPECIES_WYNAUT) { HP(500); Speed(50); Moves(MOVE_POUND); }
    } WHEN {
        TURN {
            MOVE(playerLeft, MOVE_CELEBRATE);
            MOVE(playerRight, MOVE_CELEBRATE);
            EXPECT_MOVE(opponentLeft, MOVE_SCRATCH, target: playerLeft);
            EXPECT_MOVE(opponentRight, MOVE_POUND, target: playerLeft);
        }
    } THEN {
        enum BattlerId opponentLeftBattler = GetBattlerAtPosition(B_POSITION_OPPONENT_LEFT);
        enum BattlerId opponentRightBattler = GetBattlerAtPosition(B_POSITION_OPPONENT_RIGHT);
        const struct BattleActionLogEntry *leftLog = BattleActionLog_GetLastEntry(opponentLeftBattler, 1u << B_ACTION_USE_MOVE);
        const struct BattleActionLogEntry *rightLog = BattleActionLog_GetLastEntry(opponentRightBattler, 1u << B_ACTION_USE_MOVE);

        EXPECT_EQ(gBattleActionLog.count, 4);
        EXPECT(leftLog != NULL);
        EXPECT(rightLog != NULL);
        EXPECT_EQ(leftLog->move, MOVE_SCRATCH);
        EXPECT_EQ(leftLog->target, GetBattlerAtPosition(B_POSITION_PLAYER_LEFT));
        EXPECT_EQ(rightLog->move, MOVE_POUND);
        EXPECT_EQ(rightLog->target, GetBattlerAtPosition(B_POSITION_PLAYER_LEFT));
    }
}

AI_DOUBLE_BATTLE_TEST("AI_FLAG_READ_PLAYER_MOVE: AI retargets single-target damage away from selected Protect")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_PROTECT) == EFFECT_PROTECT);
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_READ_PLAYER_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT) { HP(1); MaxHP(500); Speed(100); Moves(MOVE_PROTECT); }
        OPPONENT(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WYNAUT) { HP(500); Attack(200); Speed(50); Moves(MOVE_SCRATCH); }
    } WHEN {
        TURN {
            MOVE(playerLeft, MOVE_CELEBRATE);
            MOVE(playerRight, MOVE_PROTECT);
            EXPECT_MOVE(opponentLeft, MOVE_CELEBRATE);
            EXPECT_MOVE(opponentRight, MOVE_SCRATCH, target: playerLeft);
        }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY: AI can spend Dynamax to block phazing disruption")
{
    GIVEN {
        ASSUME(GetMoveEffect(MOVE_ROAR) == EFFECT_ROAR);
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_ROAR); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { MOVE(player, MOVE_ROAR); EXPECT_MOVE(opponent, MOVE_SCRATCH, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_AGGRESSIVE_GIMMICK: AI can spend Dynamax with reserves on a pressure turn")
{
    PASSES_RANDOMLY(AI_AGGRESSIVE_GIMMICK_USE_CHANCE, 100, RNG_AI_AGGRESSIVE_GIMMICK);
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY | AI_FLAG_AGGRESSIVE_GIMMICK);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_RAYQUAZA) { Speed(100); Moves(MOVE_DOUBLE_EDGE); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_DOUBLE_EDGE, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_DOUBLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY: AI can spend Dynamax for Max Airstream speed control")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_GUST); DynamaxLevel(10); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { EXPECT_MOVE(opponentLeft, MOVE_GUST, gimmick: GIMMICK_DYNAMAX); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_TERA_ONLY: AI can use Tera for an offensive boost")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_TERA_ONLY);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); HP(500); Speed(100); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_AQUA_TAIL); TeraType(TYPE_WATER); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_AQUA_TAIL, gimmick: GIMMICK_TERA); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_Z_MOVE: AI conserves a damaging Z-Move when it has no immediate payoff")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_SMART_GIMMICK_TIMING | AI_FLAG_SMART_Z_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); HP(500); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Item(ITEM_NORMALIUM_Z); Moves(MOVE_QUICK_ATTACK); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_QUICK_ATTACK, gimmick: GIMMICK_NONE); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_Z_MOVE: AI can spend a damaging Z-Move on its last Pokemon")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_SMART_GIMMICK_TIMING | AI_FLAG_SMART_Z_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Item(ITEM_NORMALIUM_Z); Moves(MOVE_QUICK_ATTACK); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_QUICK_ATTACK, gimmick: GIMMICK_Z_MOVE); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_Z_MOVE: AI can spend a damaging Z-Move with one reserve when low on HP")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_SMART_GIMMICK_TIMING | AI_FLAG_SMART_Z_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); HP(50); MaxHP(100); Item(ITEM_NORMALIUM_Z); Moves(MOVE_QUICK_ATTACK); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_QUICK_ATTACK, gimmick: GIMMICK_Z_MOVE); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_AGGRESSIVE_GIMMICK: AI can spend a Z-Move with reserves on a pressure turn")
{
    PASSES_RANDOMLY(AI_AGGRESSIVE_GIMMICK_USE_CHANCE, 100, RNG_AI_AGGRESSIVE_GIMMICK);
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_SMART_GIMMICK_TIMING | AI_FLAG_SMART_Z_MOVE | AI_FLAG_AGGRESSIVE_GIMMICK);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_RAYQUAZA) { Speed(100); Item(ITEM_NORMALIUM_Z); Moves(MOVE_DOUBLE_EDGE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Speed(50); Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_DOUBLE_EDGE, gimmick: GIMMICK_Z_MOVE); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_ALL: AI can spend a Z-Move from a held Z-Crystal")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_ALL);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Item(ITEM_NORMALIUM_Z); Moves(MOVE_QUICK_ATTACK); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_QUICK_ATTACK, gimmick: GIMMICK_Z_MOVE); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_ALL: AI can Mega Evolve with one reserve when low on HP")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_ALL);
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_VENUSAUR) { HP(50); MaxHP(100); Item(ITEM_VENUSAURITE); Moves(MOVE_SLUDGE_BOMB); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_SLUDGE_BOMB, gimmick: GIMMICK_MEGA); }
    } SCENE {
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_MEGA_EVOLUTION, opponent);
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_Z_MOVE: AI can spend a damaging Z-Move to pressure a trapping target")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_SMART_GIMMICK_TIMING | AI_FLAG_SMART_Z_MOVE);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_SHADOW_TAG); HP(500); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT) { Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Item(ITEM_NORMALIUM_Z); Moves(MOVE_QUICK_ATTACK); }
        OPPONENT(SPECIES_WYNAUT) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_QUICK_ATTACK, gimmick: GIMMICK_Z_MOVE); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_DYNAMAX_TERA: AI can use Tera before a Dynamax backup")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_DYNAMAX_TERA);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_AQUA_TAIL); TeraType(TYPE_WATER); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_SCRATCH); DynamaxLevel(10); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_AQUA_TAIL, gimmick: GIMMICK_TERA); }
    }
}

AI_DOUBLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_ALL: AI can use Tera in doubles")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_ALL);
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WOBBUFFET) { HP(500); Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_AQUA_TAIL); TeraType(TYPE_WATER); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponentLeft, MOVE_AQUA_TAIL, gimmick: GIMMICK_TERA); }
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_SMART_MEGA: AI can Mega Evolve for Shadow Tag board control")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_OMNISCIENT | AI_FLAG_SMART_GIMMICK_TIMING | AI_FLAG_SMART_MEGA);
        PLAYER(SPECIES_WOBBUFFET) { Ability(ABILITY_TELEPATHY); Moves(MOVE_CELEBRATE); }
        PLAYER(SPECIES_WYNAUT) { Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_GENGAR) { Item(ITEM_GENGARITE); Moves(MOVE_SLUDGE_BOMB); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_SLUDGE_BOMB, gimmick: GIMMICK_MEGA); }
    } SCENE {
        ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_MEGA_EVOLUTION, opponent);
    }
}

AI_SINGLE_BATTLE_TEST("AI_FLAG_GIMMICK_ENV_ALL: AI can delay Mega Evolution for a setup turn")
{
    GIVEN {
        AI_FLAGS(AI_FLAG_BASIC_TRAINER | AI_FLAG_FORCE_SETUP_FIRST_TURN | AI_FLAG_OMNISCIENT | AI_FLAG_GIMMICK_ENV_ALL);
        PLAYER(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
        OPPONENT(SPECIES_VENUSAUR) { Item(ITEM_VENUSAURITE); Moves(MOVE_GROWTH, MOVE_SLUDGE_BOMB); }
        OPPONENT(SPECIES_WOBBUFFET) { Moves(MOVE_CELEBRATE); }
    } WHEN {
        TURN { EXPECT_MOVE(opponent, MOVE_GROWTH, gimmick: GIMMICK_NONE); }
    } SCENE {
        NOT ANIMATION(ANIM_TYPE_GENERAL, B_ANIM_MEGA_EVOLUTION, opponent);
    }
}
