#!/usr/bin/env python3
"""
Generate area-based randomizer tables from YAML.

Input: data/randomizer/area_rules.yml
Output: generated/randomizer_area_rules.h

Features:
- Kits (reusable species lists) with apply/remove per area/gift.
- Deduplication with removal taking precedence（remove優先＋重複除去）。
- 空WL検出をエラー化。
- 追加メタ（slotMode / rareSlots / rareRate / maxSpecies / 竿別設定）のバリデーションと出力。
- ソート済みのルールで決定的な生成。

Note: Makefile統合は別ステップ。必要に応じて手動実行する。
"""

import sys
import pathlib
import argparse
import yaml
import copy
from typing import Dict, List, Optional, Tuple

SCHEMA_VERSION_EXPECTED = ("1.30", "1.40")

THIS_DIR = pathlib.Path(__file__).resolve().parent
ROOT = THIS_DIR.parent
DEFAULT_INPUT = ROOT / "data/randomizer/area_rules.yml"
DEFAULT_OUTPUT = ROOT / "generated/randomizer_area_rules.h"

HEADER_PREAMBLE = """\
// Auto-generated by build_randomizer_area_rules.py. Do not edit manually.
#pragma once
#include "global.h"
#include "constants/species.h"
#include "constants/maps.h"
#include "constants/rtc.h"
#include "constants/randomizer_slots.h"
#include "config/randomizer.h"

enum {
    RANDOMIZER_SLOT_MODE_UNIFORM = 0,
    RANDOMIZER_SLOT_MODE_RARE = 1,
};

enum {
    RANDOMIZER_ROD_OLD = 0,
    RANDOMIZER_ROD_GOOD = 1,
    RANDOMIZER_ROD_SUPER = 2,
};

enum {
    RANDOMIZER_TIME_SLOT_MORNING = 0,
    RANDOMIZER_TIME_SLOT_DAY = 1,
    RANDOMIZER_TIME_SLOT_EVENING = 2,
    RANDOMIZER_TIME_SLOT_NIGHT = 3,
    RANDOMIZER_TIME_SLOT_ANY = 0xFF,
};

enum {
    RANDOMIZER_SPECIAL_LEGEND      = 1 << 0,
    RANDOMIZER_SPECIAL_MYTHICAL    = 1 << 1,
    RANDOMIZER_SPECIAL_ULTRA_BEAST = 1 << 2,
    RANDOMIZER_SPECIAL_PARADOX     = 1 << 3,
    RANDOMIZER_SPECIAL_SUB_LEGEND  = 1 << 4,
};

struct RandomizerLevelBand {
    u8 minLevel;
    u8 maxLevel;
};

struct RandomizerFishingRule {
    u16 normalWlOffset;
    u16 normalWlCount;
    u16 normalBlOffset;
    u16 normalBlCount;
    u16 rareWlOffset;
    u16 rareWlCount;
    u16 rareBlOffset;
    u16 rareBlCount;
    u8 slotMode;
    u8 maxSpecies;
    u8 rareSlots;
    u8 rareRate;
    u8 specialOverrides;
    bool8 allowEmpty;
    u8 maxRerolls;
    u16 levelBandOffset;
    u16 levelBandCount;
    u16 rareLevelBandOffset;
    u16 rareLevelBandCount;
};

struct RandomizerAreaRule {
    u8 mapGroup;
    u8 mapNum;
    u8 areaMask;
    u8 timeSlot; // RANDOMIZER_TIME_* or 0xFF (ANY)
    u16 normalWlOffset;
    u16 normalWlCount;
    u16 normalBlOffset;
    u16 normalBlCount;
    u16 rareWlOffset;
    u16 rareWlCount;
    u16 rareBlOffset;
    u16 rareBlCount;
    u8 maxRerolls;
    u8 slotMode;
    u8 maxSpecies;
    u8 rareSlots;
    u8 rareRate;
    u8 specialOverrides;
    const struct RandomizerFishingRule *fishingRules;
    u8 fishingRuleCount;
    bool8 allowEmpty;
    u8 slotCount;
    u8 encounterRate;
    u16 weightOffset;
    u16 weightCount;
    u16 rareWeightOffset;
    u16 rareWeightCount;
    u16 levelBandOffset;
    u16 levelBandCount;
    u16 rareLevelBandOffset;
    u16 rareLevelBandCount;
};

"""


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default=str(DEFAULT_INPUT))
    ap.add_argument("--out", dest="out", default=str(DEFAULT_OUTPUT))
    ap.add_argument("--exceptions", dest="exceptions", default=str(ROOT / "data/randomizer/exception_maps.yml"))
    ap.add_argument("--exceptions-out", dest="exceptions_out", default=str(ROOT / "generated/randomizer_exceptions.h"))
    return ap.parse_args()


def load_yaml(path: pathlib.Path):
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)

ROD_CONST = {
    "old": 0,
    "good": 1,
    "super": 2,
}

def load_exceptions(data: Optional[Dict]):
    results = []
    if not data:
        return results
    entries = data.get("exceptions", [])
    if entries is None:
        entries = []
    for idx, e in enumerate(entries):
        ctx = f"exception[{idx}]"
        try:
            mapGroup = e["mapGroup"]
            mapNum = e["mapNum"]
            areaMask, _ = resolve_mask(e["areaMask"])
            timeSlot = TIME_CODE.get(e.get("timeSlot", "any"), TIME_CONST["RANDOMIZER_TIME_SLOT_ANY"])
            rod = e.get("rod", None)
            if rod is not None:
                rod = rod.lower()
                if rod not in ROD_CONST:
                    raise ValueError(f"{ctx}: unknown rod '{rod}'")
                rodType = ROD_CONST[rod]
            else:
                rodType = 0xFF  # any
            action = e.get("action", "allow")
            if action != "allow":
                raise ValueError(f"{ctx}: action must be 'allow'")
        except KeyError as err:
            raise ValueError(f"{ctx}: missing key {err}") from err
        results.append({
            "mapGroup": mapGroup,
            "mapNum": mapNum,
            "areaMask": areaMask,
            "timeSlot": timeSlot,
            "rodType": rodType,
            "action": action,
        })
    return results


def parse_schema_version(data):
    version = data.get("schemaVersion")
    if version is None:
        raise ValueError(f"schemaVersion is required (expected one of {', '.join(SCHEMA_VERSION_EXPECTED)})")
    expected_float = [float(v) for v in SCHEMA_VERSION_EXPECTED]
    if isinstance(version, (int, float)):
        if float(version) not in expected_float:
            raise ValueError(f"Unsupported schemaVersion '{version}', expected one of {SCHEMA_VERSION_EXPECTED} (future versions must match key/type layout exactly)")
        return str(version)
    version_str = str(version)
    if version_str not in SCHEMA_VERSION_EXPECTED:
        raise ValueError(f"Unsupported schemaVersion '{version_str}', expected one of {SCHEMA_VERSION_EXPECTED} (future versions must match key/type layout exactly)")
    return version_str


def resolve_mask(mask: str) -> Tuple[int, str]:
    # Accept string names for readability
    mask_map = {
        "Land": (1 << 0, "Land"),
        "Water": (1 << 1, "Water"),
        "Fishing": (1 << 2, "Fishing"),
        "Fish": (1 << 2, "Fishing"),  # backward compatibility
        "Rock": (1 << 3, "Rock"),
        "Rocks": (1 << 3, "Rock"),  # backward compatibility
        "Hidden": (1 << 4, "Hidden"),
        "Gift": (1 << 5, "Gift"),
    }
    if isinstance(mask, int):
        # int指定は非推奨だが通す（1ビットのみを許容）
        if mask == 0 or mask & (mask - 1):
            raise ValueError(f"areaMask int '{mask}' must be a single bit")
        return mask, "Custom"
    if isinstance(mask, str):
        parts = [p.strip() for p in mask.split(",")]
        if len(parts) != 1:
            raise ValueError(f"areaMask must be a single entry (got '{mask}')")
        part = parts[0]
        if part not in mask_map:
            raise ValueError(f"Unknown areaMask '{part}'")
        return mask_map[part]
    raise ValueError(f"Unsupported areaMask type: {mask}")


def parse_slot_mode(slot_mode: Optional[str]) -> int:
    if slot_mode is None:
        return 0
    if isinstance(slot_mode, int):
        if slot_mode in (0, 1):
            return slot_mode
        raise ValueError(f"slotMode int must be 0 or 1 (got {slot_mode})")
    if isinstance(slot_mode, str):
        lower = slot_mode.lower()
        if lower == "uniform":
            return 0
        if lower == "rare":
            return 1
    raise ValueError(f"Unsupported slotMode '{slot_mode}'")


TIME_KEYS = ("morning", "day", "evening", "night", "any", "false")
TIME_CODE = {
    "morning": 0,
    "day": 1,
    "evening": 2,
    "night": 3,
    "any": 0xFF,
    "false": 0xFF,
}
RANDOMIZER_SLOT_MODE_UNIFORM = 0
RANDOMIZER_SLOT_MODE_RARE = 1

# 定数値の簡易解決（文字列指定を許容するため）
SLOT_LIMIT_CONST = {
    "LAND_MAX_SLOTS": 12,
    "WATER_MAX_SLOTS": 5,
    "ROCK_MAX_SLOTS": 5,
    "FISH_MAX_SLOTS": 12,
}
TIME_CONST = {
    "RANDOMIZER_TIME_SLOT_MORNING": 0,
    "RANDOMIZER_TIME_SLOT_DAY": 1,
    "RANDOMIZER_TIME_SLOT_EVENING": 2,
    "RANDOMIZER_TIME_SLOT_NIGHT": 3,
    "RANDOMIZER_TIME_SLOT_ANY": 0xFF,
}
SPECIAL_MASK_ALL = (
    (1 << 0) |  # legend
    (1 << 1) |  # mythical
    (1 << 2) |  # ub
    (1 << 3) |  # paradox
    (1 << 4)    # subLegend
)

# New fields defaults for slotSets-based weighted slots (v1.40 draft)
DEFAULT_SLOT_MODE = RANDOMIZER_SLOT_MODE_UNIFORM
DEFAULT_WEIGHT_MODE = "vanilla"  # when weights are absent
DEFAULT_RARE_SLOTS = 0
DEFAULT_ENCOUNTER_RATE = 0

# areaMaskごとのスロット上限（maxSpecies上限）
AREA_SLOT_LIMITS = {
    "Land": SLOT_LIMIT_CONST["LAND_MAX_SLOTS"],
    "Water": SLOT_LIMIT_CONST["WATER_MAX_SLOTS"],
    "Rock": SLOT_LIMIT_CONST["ROCK_MAX_SLOTS"],
    "Fishing": SLOT_LIMIT_CONST["FISH_MAX_SLOTS"],  # 実際にはrod別で制限
    "Hidden": SLOT_LIMIT_CONST["LAND_MAX_SLOTS"],  # fallback
    "Gift": 6,     # partyサイズ相当を上限としておく
}

ROD_SLOT_LIMITS = {
    "old": 2,
    "good": 5,
    "super": 5,
}


def dedup_apply_remove(apply_list, remove_list):
    wl = []
    seen = set()
    remove_set = set(remove_list or [])
    for s in apply_list or []:
        if s in remove_set:
            continue
        if s in seen:
            continue
        wl.append(s)
        seen.add(s)
    return wl, sorted(remove_set)


def block_has_content(block: Optional[Dict]) -> bool:
    if not block:
        return False
    if block.get("apply") or block.get("remove"):
        return True
    if "rareRate" in block or "rareSlots" in block:
        return True
    return False


def rod_has_data(block: Optional[Dict]) -> bool:
    if not block:
        return False
    if block_has_content(block.get("default")) or block_has_content(block.get("rare")):
        return True
    for key in ("slotMode", "maxSpecies", "maxRerolls", "specialOverrides"):
        if key in block:
            return True
    return False


def entry_has_data(block: Optional[Dict]) -> bool:
    if not block:
        return False
    if block_has_content(block.get("default")) or block_has_content(block.get("rare")):
        return True
    fishing_block = block.get("fishing")
    if fishing_block is not None:
        if fishing_block:
            return True
        for rod_block in (fishing_block or {}).values():
            if rod_has_data(rod_block):
                return True
    for key in ("slotMode", "maxSpecies", "maxRerolls", "specialOverrides"):
        if key in block:
            return True
    return False


def merge_block(base: Optional[Dict], override: Optional[Dict]) -> Dict:
    result = copy.deepcopy(base) if base else {}
    if override:
        for k, v in override.items():
            result[k] = copy.deepcopy(v)
    return result

def merge_slotset(base: Optional[Dict], override: Optional[Dict]) -> Dict:
    """slotSetに maxSpecies/maxRerolls などを含める場合のマージ。"""
    return merge_block(base, override)


def merge_rod(base: Optional[Dict], override: Optional[Dict]) -> Dict:
    result = merge_block(base, override)
    base_allow = bool((base or {}).get("allowEmpty", False))
    data_written = rod_has_data(override)
    if override and "allowEmpty" in override:
        allow = bool(override.get("allowEmpty", False))
    elif data_written:
        allow = False
    else:
        allow = base_allow
    result["allowEmpty"] = bool(allow)
    return result


def merge_fishing(base: Optional[Dict], override: Optional[Dict]) -> Dict:
    base_fish = base or {}
    override_fish = override or {}
    merged: Dict = {}
    for rod in set(base_fish.keys()) | set(override_fish.keys()):
        merged[rod] = merge_rod(base_fish.get(rod), override_fish.get(rod))
    return merged


def merge_entry(base: Optional[Dict], override: Optional[Dict]) -> Dict:
    base_entry = base or {}
    override_entry = override or {}
    result = merge_block(base_entry, override_entry)
    if "fishing" in base_entry or "fishing" in override_entry:
        result["fishing"] = merge_fishing(base_entry.get("fishing"), override_entry.get("fishing"))
    data_written = entry_has_data(override_entry)
    base_allow = bool(base_entry.get("allowEmpty", False))
    if "allowEmpty" in override_entry:
        allow = bool(override_entry.get("allowEmpty", False))
    elif data_written:
        allow = False
    else:
        allow = base_allow
    result["allowEmpty"] = bool(allow)
    return result


def render_array(name, entries):
    lines = [f"static const u16 {name}[] = {{"]
    for s in entries:
        lines.append(f"    {s},")
    lines.append("};\n")
    return "\n".join(lines)


def parse_int(value, ctx: str, allow_null: bool = False):
    if value is None:
        if allow_null:
            return None
        raise ValueError(f"{ctx}: value is required")
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        if value.lower() == "auto":
            return "auto"
        if value in SLOT_LIMIT_CONST:
            return SLOT_LIMIT_CONST[value]
        if value in TIME_CONST:
            return TIME_CONST[value]
        try:
            return int(value, 0)
        except Exception:
            raise ValueError(f"{ctx}: cannot parse int from '{value}'")
    raise ValueError(f"{ctx}: unsupported type for int conversion: {type(value)}")


def main():
    args = parse_args()
    inp = pathlib.Path(args.inp)
    out = pathlib.Path(args.out)
    exc_in = pathlib.Path(args.exceptions)
    exc_out = pathlib.Path(args.exceptions_out)
    data = load_yaml(inp)
    parse_schema_version(data)
    exceptions_data = None
    if exc_in.exists():
        exceptions_data = load_yaml(exc_in)
        parse_schema_version(exceptions_data)

    kits = data.get("kits", {})
    slot_sets = data.get("slotSets", {})
    areas = data.get("areas", {})
    gifts = data.get("gifts", {})

    wl_pool: List[str] = []
    bl_pool: List[str] = []
    weight_pool: List[int] = []
    rare_weight_pool: List[int] = []
    level_band_pool: List[Tuple[int, int]] = []
    rare_level_band_pool: List[Tuple[int, int]] = []
    rules: List[Dict] = []
    fishing_rules: List[Dict] = []

    def add_pool_entries(wl, bl):
        nonlocal wl_pool, bl_pool
        wl_offset = len(wl_pool)
        bl_offset = len(bl_pool)
        wl_pool.extend(wl)
        bl_pool.extend(bl)
        return wl_offset, len(wl), bl_offset, len(bl)

    def add_weight_entries(weights, pool: List[int]):
        offset = len(pool)
        pool.extend(weights)
        return offset, len(weights)

    def add_level_entries(bands: List[Tuple[int, int]], pool: List[Tuple[int, int]]):
        offset = len(pool)
        pool.extend(bands)
        return offset, len(bands)

    def expand_kits(names, ctx):
        result = []
        for kit_name in names or []:
            if kit_name not in kits:
                raise ValueError(f"{ctx}: Unknown kit '{kit_name}'")
            result.extend(kits[kit_name])
        return result

    def build_pool(block, ctx):
        if block is None:
            return [], []
        apply_list = expand_kits(block.get("apply", []), ctx)
        remove_list = expand_kits(block.get("remove", []), ctx)
        return dedup_apply_remove(apply_list, remove_list)

    def validate_rare(ctx: str, slot_mode: int, rare_slots, rare_rate, max_species: Optional[int], slot_limit: Optional[int], allow_empty: bool):
        rs = 0 if rare_slots is None else rare_slots
        rr = 0 if rare_rate is None else rare_rate
        if slot_mode == RANDOMIZER_SLOT_MODE_UNIFORM:
            if rs or rr:
                raise ValueError(f"{ctx}: slotMode=uniform cannot have rareRate/rareSlots")
        if rs == 0 and rr > 0:
            raise ValueError(f"{ctx}: rareSlots=0 with rareRate>0 is invalid")
        if rs > 0 and rr == 0:
            raise ValueError(f"{ctx}: rareSlots>0 with rareRate=0 is invalid")
        if rr < 0 or rr > 100:
            raise ValueError(f"{ctx}: rareRate must be 0-100 (got {rr})")
        if rs < 0:
            raise ValueError(f"{ctx}: rareSlots must be >=0 (got {rs})")
        if max_species not in (None, 0) and rs > max_species:
            raise ValueError(f"{ctx}: rareSlots {rs} exceeds maxSpecies {max_species}")
        if slot_limit is not None and rs > slot_limit:
            raise ValueError(f"{ctx}: rareSlots {rs} exceeds slot limit {slot_limit}")
        if slot_mode == RANDOMIZER_SLOT_MODE_RARE and rs == 0 and rr == 0 and not allow_empty:
            raise ValueError(f"{ctx}: slotMode=rare requires rareRate/rareSlots")

    def ensure_non_empty(wl, allow_empty, ctx):
        if len(wl) == 0 and not allow_empty:
            raise ValueError(f"{ctx}: whitelist empty and allowEmpty is false")

    SPECIAL_KEYS = ("legend", "mythical", "ub", "paradox", "subLegend")

    def parse_special_overrides(entry, fallback_entry, ctx):
        """
        Returns bitmask of special categories.
        If neither entry provides specialOverrides, default to all enabled (compat維持)。
        """
        src = entry.get("specialOverrides", None)
        if src is None and fallback_entry is not None:
            src = fallback_entry.get("specialOverrides", None)

        # default: all enabled (legend/mythical/ub/paradox/subLegend)
        mask = SPECIAL_MASK_ALL
        if src is None:
            return mask
        if not isinstance(src, dict):
            raise ValueError(f"{ctx}: specialOverrides must be a mapping")
        mask = 0
        for key in SPECIAL_KEYS:
            val = src.get(key, False)
            if val:
                if key == "legend":
                    mask |= (1 << 0)
                elif key == "mythical":
                    mask |= (1 << 1)
                elif key == "ub":
                    mask |= (1 << 2)
                elif key == "paradox":
                    mask |= (1 << 3)
                elif key == "subLegend":
                    mask |= (1 << 4)
        return mask

    def extract_weights(entry: Dict, base_entry: Dict, slot_count: int, ctx: str):
        weights = entry.get("weights")
        rare_weights = entry.get("rareWeights")
        weight_mode = entry.get("weightMode", base_entry.get("weightMode", DEFAULT_WEIGHT_MODE))
        rare_slots = entry.get("rareSlots", base_entry.get("rareSlots", 0))

        if weights is not None and weight_mode is not None:
            raise ValueError(f"{ctx}: weights and weightMode cannot both be set")
        if weights is None and weight_mode is None:
            weight_mode = DEFAULT_WEIGHT_MODE

        if weights is None:
            if weight_mode == "vanilla":
                weights = []
            elif weight_mode == "even":
                weights = [0] * slot_count
                if slot_count > 0:
                    even = 100 // slot_count
                    weights = [even] * slot_count
                    # adjust remainder
                    if weights:
                        weights[0] += 100 - even * slot_count
            else:
                raise ValueError(f"{ctx}: unknown weightMode '{weight_mode}'")
        if rare_weights is None:
            if weight_mode == "vanilla":
                rare_weights = []
            elif weight_mode == "even":
                rare_weights = [0] * rare_slots
                if rare_slots > 0:
                    even = 100 // rare_slots
                    rare_weights = [even] * rare_slots
                    if rare_weights:
                        rare_weights[0] += 100 - even * rare_slots
        return weights, rare_weights

    def validate_weights(weights, expected, ctx):
        if weights is None:
            return
        if expected == 0 and len(weights) > 0:
            raise ValueError(f"{ctx}: slotCount=0 but weights provided")
        if expected != 0 and len(weights) != expected:
            raise ValueError(f"{ctx}: weights length {len(weights)} != slotCount {expected}")
        total = sum(weights)
        if total != 100 and len(weights) > 0:
            raise ValueError(f"{ctx}: weights sum {total} != 100")
        if any(w < 0 for w in weights):
            raise ValueError(f"{ctx}: weights must be non-negative")

    def extract_level_bands(entry: Dict, slot_count: int, ctx: str, key_name: str):
        bands = entry.get(key_name)
        if bands is None:
            return []
        result = []
        for idx, band in enumerate(bands):
            try:
                minLv = int(band.get("minLv"))
                maxLv = int(band.get("maxLv"))
            except Exception:
                raise ValueError(f"{ctx}: {key_name}[{idx}] must have minLv/maxLv ints")
            if minLv > maxLv:
                raise ValueError(f"{ctx}: {key_name}[{idx}] minLv > maxLv")
            if maxLv > 100:
                raise ValueError(f"{ctx}: {key_name}[{idx}] maxLv > 100")
            result.append((minLv, maxLv))
        if slot_count == 0 and len(result) > 0:
            raise ValueError(f"{ctx}: slotCount=0 but {key_name} provided")
        if slot_count != 0 and len(result) not in (0, slot_count):
            raise ValueError(f"{ctx}: {key_name} length {len(result)} != slotCount {slot_count}")
        return result

    def extract_level_bands_raw(entry: Dict, expected: int, ctx: str, key_name: str):
        bands = entry.get(key_name)
        if bands is None:
            return []
        result = []
        for idx, band in enumerate(bands):
            try:
                minLv = int(band.get("minLv"))
                maxLv = int(band.get("maxLv"))
            except Exception:
                raise ValueError(f"{ctx}: {key_name}[{idx}] must have minLv/maxLv ints")
            if minLv > maxLv:
                raise ValueError(f"{ctx}: {key_name}[{idx}] minLv > maxLv")
            if maxLv > 100:
                raise ValueError(f"{ctx}: {key_name}[{idx}] maxLv > 100")
            result.append((minLv, maxLv))
        if expected == 0 and len(result) > 0:
            raise ValueError(f"{ctx}: slotCount=0 but {key_name} provided")
        if expected != 0 and len(result) not in (0, expected):
            raise ValueError(f"{ctx}: {key_name} length {len(result)} != slotCount {expected}")
        return result

    def process_time_slot(name, entry, time_key: str, ts_entry: Dict):
        nonlocal wl_pool, bl_pool, rules, fishing_rules
        key = entry.get("key")
        if key is None:
            raise ValueError(f"{name}: key is required")
        mapGroup = key["mapGroup"]
        mapNum = key["mapNum"]
        areaMask, areaName = resolve_mask(key["areaMask"])

        if "allowLegendOverride" in entry or "allowLegendOverride" in ts_entry:
            raise ValueError(f"{name}/{time_key}: allowLegendOverride is deprecated; use specialOverrides.legend instead")

        slot_mode = parse_slot_mode(ts_entry.get("slotMode", entry.get("slotMode")))
        max_species = parse_int(ts_entry.get("maxSpecies", entry.get("maxSpecies")), f"{name}/{time_key}/maxSpecies")
        max_rerolls_raw = parse_int(ts_entry.get("maxRerolls", entry.get("maxRerolls")), f"{name}/{time_key}/maxRerolls", allow_null=True)
        allow_empty = bool(ts_entry.get("allowEmpty", entry.get("allowEmpty", False)))
        special_mask = parse_special_overrides(ts_entry, entry, f"{name}/{time_key}")
        slot_count = parse_int(ts_entry.get("slotCount", entry.get("slotCount", None)), f"{name}/{time_key}/slotCount", allow_null=True)
        encounter_rate = parse_int(ts_entry.get("encounterRate", entry.get("encounterRate", None)), f"{name}/{time_key}/encounterRate", allow_null=True)

        slot_limit = AREA_SLOT_LIMITS.get(areaName)
        if slot_limit is None:
            raise ValueError(f"{name}/{time_key}: slot limit undefined for area {areaName}")
        if max_species <= 0 and not allow_empty:
            raise ValueError(f"{name}/{time_key}: maxSpecies must be >0 (or allowEmpty true)")
        if max_species > slot_limit:
            raise ValueError(f"{name}/{time_key}: maxSpecies {max_species} exceeds slot limit {slot_limit}")
        if slot_count is None:
            slot_count = 0
        if allow_empty:
            if slot_count != 0:
                raise ValueError(f"{name}/{time_key}: allowEmpty=true requires slotCount=0")
            if encounter_rate is not None:
                raise ValueError(f"{name}/{time_key}: allowEmpty=true requires encounterRate to be unspecified")
        else:
            if encounter_rate is None:
                raise ValueError(f"{name}/{time_key}: encounterRate must be specified (slotSet or timeSlot)")

        # build pools for area (non-fishing) default/rare
        default_block = ts_entry.get("default")
        rare_block = ts_entry.get("rare")
        wl_normal, bl_normal = build_pool(default_block, f"{name}/{time_key}/default")
        wl_rare, bl_rare = build_pool(rare_block, f"{name}/{time_key}/rare")
        wl_effective = len(wl_normal) - len(bl_normal)
        if wl_effective < 0:
            wl_effective = 0

        base_rare_rate = entry.get("rareRate", None)
        base_rare_slots = entry.get("rareSlots", None)
        rare_rate = parse_int(rare_block.get("rareRate"), f"{name}/{time_key}/rareRate", allow_null=True) if rare_block is not None else None
        rare_slots = parse_int(rare_block.get("rareSlots"), f"{name}/{time_key}/rareSlots", allow_null=True) if rare_block is not None else None
        if rare_block is not None:
            if slot_mode == RANDOMIZER_SLOT_MODE_RARE:
                if rare_rate is None or rare_slots is None:
                    raise ValueError(f"{name}/{time_key}: slotMode=rare override requires rareRate and rareSlots (null is invalid)")
            else:
                # uniformなどの場合は、nullならベースを継承、片方だけはエラー
                if rare_rate is None and rare_slots is None:
                    rare_rate = base_rare_rate
                    rare_slots = base_rare_slots
                elif rare_rate is None or rare_slots is None:
                    raise ValueError(f"{name}/{time_key}: override rareRate/rareSlots requires both to be set (null is invalid)")
        else:
            rare_rate = base_rare_rate
            rare_slots = base_rare_slots
        if slot_mode == RANDOMIZER_SLOT_MODE_RARE and (rare_rate is None or rare_slots is None):
            raise ValueError(f"{name}/{time_key}: slotMode=rare requires rareRate and rareSlots (null found)")
        validate_rare(f"{name}/{time_key}", slot_mode, rare_slots, rare_rate, max_species, slot_limit, allow_empty)
        if slot_mode == RANDOMIZER_SLOT_MODE_RARE and rare_slots and not wl_rare and not allow_empty:
            raise ValueError(f"{name}/{time_key}: slotMode=rare but rare whitelist is empty")
        if allow_empty:
            if wl_normal or wl_rare:
                raise ValueError(f"{name}/{time_key}: allowEmpty=true but whitelist is not empty")
        # Fishingはrod側でデータを持つため、メインWL空でも許容
        if areaName != "Fishing":
            ensure_non_empty(wl_normal, allow_empty, f"{name}/{time_key}")

        # maxRerolls auto対応: 有効WL数を基準に推奨値を計算（上限8、最低1）
        if max_rerolls_raw == "auto":
            if allow_empty and wl_effective == 0:
                max_rerolls = 0
            else:
                mr = wl_effective if wl_effective > 0 else 1
                if mr > 8:
                    mr = 8
                max_rerolls = mr
        else:
            max_rerolls = max_rerolls_raw if max_rerolls_raw is not None else 0
        wl_norm_off, wl_norm_cnt, bl_norm_off, bl_norm_cnt = add_pool_entries(wl_normal, bl_normal)
        wl_rare_off, wl_rare_cnt, bl_rare_off, bl_rare_cnt = add_pool_entries(wl_rare, bl_rare) if wl_rare or bl_rare else (0, 0, 0, 0)

        weights = []
        rare_weights = []
        level_bands = []
        rare_level_bands = []

        # Extract weights/level bands (slotCount-based). This is proto support; if invalid, just error.
        weights, rare_weights = extract_weights(ts_entry, entry, slot_count, f"{name}/{time_key}")
        validate_weights(weights, slot_count, f"{name}/{time_key}/weights")
        validate_weights(rare_weights, rare_slots if rare_slots else 0, f"{name}/{time_key}/rareWeights")
        level_bands = extract_level_bands(ts_entry, slot_count, f"{name}/{time_key}", "levelBands")
        rare_level_bands = extract_level_bands(ts_entry, rare_slots if rare_slots else 0, f"{name}/{time_key}", "rareLevelBands")

        weight_off, weight_cnt = (0, 0)
        rare_weight_off, rare_weight_cnt = (0, 0)
        level_off, level_cnt = (0, 0)
        rare_level_off, rare_level_cnt = (0, 0)

        if weights:
            weight_off, weight_cnt = add_weight_entries(weights, weight_pool)
        if rare_weights:
            rare_weight_off, rare_weight_cnt = add_weight_entries(rare_weights, rare_weight_pool)
        if level_bands:
            level_off, level_cnt = add_level_entries(level_bands, level_band_pool)
        if rare_level_bands:
            rare_level_off, rare_level_cnt = add_level_entries(rare_level_bands, rare_level_band_pool)

        fishing_offset = 0
        fishing_count = 0

        if areaName == "Fishing":
            fishing = ts_entry.get("fishing")
            if fishing is None and not allow_empty:
                raise ValueError(f"{name}/{time_key}: fishing block required for Fish area")
            if fishing is None and allow_empty and not ts_entry.get("allowEmpty", False):
                raise ValueError(f"{name}/{time_key}: allowEmpty=true for Fishing requires allowEmpty:true in timeSlot (empty block is not allowed)")

            fishing_offset = len(fishing_rules)
            rod_rules = []
            for rod in ("old", "good", "super"):
                rod_data = (fishing or {}).get(rod)
                if rod_data is None:
                    if allow_empty:
                        rod_rules.append({
                            "normal": (0, 0, 0, 0),
                            "rare": (0, 0, 0, 0),
                            "slotMode": RANDOMIZER_SLOT_MODE_UNIFORM,
                            "maxSpecies": 0,
                            "rareSlots": 0,
                            "rareRate": 0,
                            "specialOverrides": SPECIAL_MASK_ALL,
                            "allowEmpty": 1,
                            "maxRerolls": 0,
                        })
                        continue
                    raise ValueError(f"{name}/{time_key}: missing rod '{rod}'")
                if "allowLegendOverride" in rod_data:
                    raise ValueError(f"{name}/{time_key}/fishing/{rod}: allowLegendOverride is deprecated; use specialOverrides.legend")
                rod_slot_mode = parse_slot_mode(rod_data.get("slotMode", slot_mode))
                rod_max_species = parse_int(rod_data.get("maxSpecies", ROD_SLOT_LIMITS[rod]), f"{name}/{time_key}/fishing/{rod}/maxSpecies", allow_null=allow_empty)
                rod_max_rerolls = parse_int(rod_data.get("maxRerolls", max_rerolls), f"{name}/{time_key}/fishing/{rod}/maxRerolls", allow_null=allow_empty)
                rod_allow_empty = bool(rod_data.get("allowEmpty", allow_empty))
                rod_special_mask = parse_special_overrides(rod_data, ts_entry, f"{name}/{time_key}/fishing/{rod}")

                rod_default = rod_data.get("default")
                rod_rare = rod_data.get("rare")
                rod_wl_norm, rod_bl_norm = build_pool(rod_default, f"{name}/{time_key}/fishing/{rod}/default")
                rod_wl_rare, rod_bl_rare = build_pool(rod_rare, f"{name}/{time_key}/fishing/{rod}/rare")
                rod_rare_rate = parse_int((rod_rare or {}).get("rareRate"), f"{name}/{time_key}/fishing/{rod}/rareRate", allow_null=True)
                rod_rare_slots = parse_int((rod_rare or {}).get("rareSlots"), f"{name}/{time_key}/fishing/{rod}/rareSlots", allow_null=True)
                validate_rare(f"{name}/{time_key}/fishing/{rod}", rod_slot_mode, rod_rare_slots, rod_rare_rate, rod_max_species, ROD_SLOT_LIMITS[rod], rod_allow_empty)
                if rod_allow_empty:
                    if rod_wl_norm or rod_wl_rare:
                        raise ValueError(f"{name}/{time_key}/fishing/{rod}: allowEmpty=true but whitelist is not empty")
                ensure_non_empty(rod_wl_norm, rod_allow_empty, f"{name}/{time_key}/fishing/{rod}")

                rod_level_bands = extract_level_bands_raw(rod_data, rod_max_species if rod_max_species else 0, f"{name}/{time_key}/fishing/{rod}", "levelBands")
                rod_rare_level_bands = extract_level_bands_raw(rod_data, rod_rare_slots if rod_rare_slots else 0, f"{name}/{time_key}/fishing/{rod}", "rareLevelBands")

                if rod_allow_empty:
                    if rod_level_bands or rod_rare_level_bands:
                        raise ValueError(f"{name}/{time_key}/fishing/{rod}: allowEmpty=true but levelBands provided")

                n_off, n_cnt, nb_off, nb_cnt = add_pool_entries(rod_wl_norm, rod_bl_norm)
                r_off, r_cnt, rb_off, rb_cnt = add_pool_entries(rod_wl_rare, rod_bl_rare) if rod_wl_rare or rod_bl_rare else (0, 0, 0, 0)

                rod_level_off, rod_level_cnt = (0, 0)
                rod_rare_level_off, rod_rare_level_cnt = (0, 0)
                if rod_level_bands:
                    rod_level_off, rod_level_cnt = add_level_entries(rod_level_bands, level_band_pool)
                if rod_rare_level_bands:
                    rod_rare_level_off, rod_rare_level_cnt = add_level_entries(rod_rare_level_bands, rare_level_band_pool)

                rod_rules.append({
                    "normal": (n_off, n_cnt, nb_off, nb_cnt),
                    "rare": (r_off, r_cnt, rb_off, rb_cnt),
                    "slotMode": rod_slot_mode,
                    "maxSpecies": rod_max_species if rod_max_species is not None else 0,
                    "rareSlots": 0 if rod_rare_slots is None else rod_rare_slots,
                    "rareRate": 0 if rod_rare_rate is None else rod_rare_rate,
                    "specialOverrides": rod_special_mask,
                    "allowEmpty": 1 if rod_allow_empty else 0,
                    "maxRerolls": 0 if rod_max_rerolls is None else rod_max_rerolls,
                    "levelBands": (rod_level_off, rod_level_cnt),
                    "rareLevelBands": (rod_rare_level_off, rod_rare_level_cnt),
                })

            fishing_count = len(rod_rules)
            fishing_rules.extend(rod_rules)

        rule = {
            "mapGroup": mapGroup,
            "mapNum": mapNum,
            "areaMask": areaMask,
            "timeSlot": TIME_CODE[time_key],
            "normal": (wl_norm_off, wl_norm_cnt, bl_norm_off, bl_norm_cnt),
            "rare": (wl_rare_off, wl_rare_cnt, bl_rare_off, bl_rare_cnt),
            "maxRerolls": max_rerolls if max_rerolls is not None else 0,
            "slotMode": slot_mode,
            "maxSpecies": max_species if max_species is not None else 0,
            "rareSlots": 0 if rare_slots is None else rare_slots,
            "rareRate": 0 if rare_rate is None else rare_rate,
            "fishingOffset": fishing_offset,
            "fishingCount": fishing_count,
            "specialOverrides": special_mask,
            "allowEmpty": 1 if allow_empty else 0,
            "slotCount": slot_count if slot_count is not None else 0,
            "encounterRate": encounter_rate if encounter_rate is not None else 0,
            "weightOffset": weight_off,
            "weightCount": weight_cnt,
            "rareWeightOffset": rare_weight_off,
            "rareWeightCount": rare_weight_cnt,
            "levelBandOffset": level_off,
            "levelBandCount": level_cnt,
            "rareLevelBandOffset": rare_level_off,
            "rareLevelBandCount": rare_level_cnt,
        }
        rules.append(rule)

    def apply_slot_set(entry: Dict) -> Dict:
        """Merge slotSet template into area entry."""
        if "slotSet" not in entry:
            return entry
        set_name = entry["slotSet"]
        if set_name not in slot_sets:
            raise ValueError(f"{set_name}: slotSet is not defined")
        base = dict(slot_sets[set_name] or {})
        merged = dict(base)
        merged.update(entry)
        # map slotCount -> maxSpecies if not explicitly set
        if "maxSpecies" not in merged and "slotCount" in merged and merged["slotCount"] is not None:
            merged["maxSpecies"] = merged["slotCount"]
        merged.pop("slotSet", None)
        return merged

    def process_entry(name, entry):
        entry = apply_slot_set(entry)
        time_slots_block = entry.get("timeSlots")
        if time_slots_block is None:
            raise ValueError(f"{name}: timeSlots is required (any/false/morning/day/evening/night)")
        if time_slots_block is False:
            ts_map = {"false": {}}
        else:
            ts_map = dict(time_slots_block)

        invalid_keys = [k for k in ts_map.keys() if k not in TIME_KEYS]
        if invalid_keys:
            raise ValueError(f"{name}: unknown timeSlots key(s): {invalid_keys}")

        if "false" in ts_map:
            if len(ts_map) > 1:
                raise ValueError(f"{name}: timeSlots false cannot be mixed with other keys")
            process_time_slot(name, entry, "false", ts_map["false"] or {})
            return

        keys = set(ts_map.keys())
        has_any = "any" in keys
        if not has_any and keys != {"morning", "day", "evening", "night"}:
            raise ValueError(f"{name}/timeSlots: invalid pattern (use 'any', 'any+partial times', or all morning/day/evening/night)")

        if has_any and not keys.issubset({"any", "morning", "day", "evening", "night"}):
            raise ValueError(f"{name}/timeSlots: invalid pattern (use 'any', 'any+partial times', or all morning/day/evening/night)")

        base_any = ts_map.get("any")
        specific_keys = keys - {"any"}

        if has_any and not specific_keys:
            process_time_slot(name, entry, "any", base_any or {})
            return

        if has_any:
            base_entry = base_any or {}
            for tkey in ("morning", "day", "evening", "night"):
                merged = merge_entry(base_entry, ts_map.get(tkey))
                process_time_slot(name, entry, tkey, merged or {})
            return

        # no any: must be full set of 4 keys (checked above)
        for tkey in ("morning", "day", "evening", "night"):
            process_time_slot(name, entry, tkey, ts_map[tkey] or {})

    for name, entry in areas.items():
        process_entry(name, entry)
    for name, entry in gifts.items():
        process_entry(f"gift_{name}", entry)

    rules.sort(key=lambda r: (str(r["mapGroup"]), str(r["mapNum"]), r["areaMask"], r["timeSlot"]))

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write(HEADER_PREAMBLE)
        f.write(render_array("sRandomizerAreaWhitelistPool", wl_pool))
        f.write(render_array("sRandomizerAreaBlacklistPool", bl_pool))
        f.write(render_array("sRandomizerAreaWeightPool", weight_pool))
        f.write(render_array("sRandomizerAreaRareWeightPool", rare_weight_pool))

        f.write("static const struct RandomizerLevelBand sRandomizerAreaLevelBandPool[] = {\n")
        for band in level_band_pool:
            f.write(f"    {{ .minLevel = {band[0]}, .maxLevel = {band[1]} }},\n")
        f.write("};\n\n")

        f.write("static const struct RandomizerLevelBand sRandomizerAreaRareLevelBandPool[] = {\n")
        for band in rare_level_band_pool:
            f.write(f"    {{ .minLevel = {band[0]}, .maxLevel = {band[1]} }},\n")
        f.write("};\n\n")

        # Fishing rules table
        f.write("static const struct RandomizerFishingRule sRandomizerFishingRules[] = {\n")
        for fr in fishing_rules:
            f.write("    {\n")
            f.write(f"        .normalWlOffset = {fr['normal'][0]},\n")
            f.write(f"        .normalWlCount = {fr['normal'][1]},\n")
            f.write(f"        .normalBlOffset = {fr['normal'][2]},\n")
            f.write(f"        .normalBlCount = {fr['normal'][3]},\n")
            f.write(f"        .rareWlOffset = {fr['rare'][0]},\n")
            f.write(f"        .rareWlCount = {fr['rare'][1]},\n")
            f.write(f"        .rareBlOffset = {fr['rare'][2]},\n")
            f.write(f"        .rareBlCount = {fr['rare'][3]},\n")
            f.write(f"        .slotMode = {fr['slotMode']},\n")
            f.write(f"        .maxSpecies = {fr['maxSpecies']},\n")
            f.write(f"        .rareSlots = {fr['rareSlots']},\n")
            f.write(f"        .rareRate = {fr['rareRate']},\n")
            f.write(f"        .specialOverrides = {fr.get('specialOverrides', SPECIAL_MASK_ALL)},\n")
            f.write(f"        .allowEmpty = {fr.get('allowEmpty', 0)},\n")
            f.write(f"        .maxRerolls = {fr.get('maxRerolls', 0)},\n")
            f.write(f"        .levelBandOffset = {fr.get('levelBands', (0,0))[0]},\n")
            f.write(f"        .levelBandCount = {fr.get('levelBands', (0,0))[1]},\n")
            f.write(f"        .rareLevelBandOffset = {fr.get('rareLevelBands', (0,0))[0]},\n")
            f.write(f"        .rareLevelBandCount = {fr.get('rareLevelBands', (0,0))[1]},\n")
            f.write("    },\n")
        f.write("};\n\n")

        f.write("static const struct RandomizerAreaRule sRandomizerAreaRules[] = {\n")
        for r in rules:
            f.write("    {\n")
            f.write(f"        .mapGroup = {r['mapGroup']},\n")
            f.write(f"        .mapNum = {r['mapNum']},\n")
            f.write(f"        .areaMask = {r['areaMask']},\n")
            f.write(f"        .timeSlot = {r['timeSlot']},\n")
            f.write(f"        .normalWlOffset = {r['normal'][0]},\n")
            f.write(f"        .normalWlCount = {r['normal'][1]},\n")
            f.write(f"        .normalBlOffset = {r['normal'][2]},\n")
            f.write(f"        .normalBlCount = {r['normal'][3]},\n")
            f.write(f"        .rareWlOffset = {r['rare'][0]},\n")
            f.write(f"        .rareWlCount = {r['rare'][1]},\n")
            f.write(f"        .rareBlOffset = {r['rare'][2]},\n")
            f.write(f"        .rareBlCount = {r['rare'][3]},\n")
            f.write(f"        .maxRerolls = {r['maxRerolls']},\n")
            f.write(f"        .slotMode = {r['slotMode']},\n")
            f.write(f"        .maxSpecies = {r['maxSpecies']},\n")
            f.write(f"        .rareSlots = {r['rareSlots']},\n")
            f.write(f"        .rareRate = {r['rareRate']},\n")
            f.write(f"        .specialOverrides = {r['specialOverrides']},\n")
            if r["fishingCount"] > 0:
                f.write(f"        .fishingRules = &sRandomizerFishingRules[{r['fishingOffset']}],\n")
                f.write(f"        .fishingRuleCount = {r['fishingCount']},\n")
            else:
                f.write("        .fishingRules = NULL,\n")
                f.write("        .fishingRuleCount = 0,\n")
            f.write(f"        .allowEmpty = {r['allowEmpty']},\n")
            f.write(f"        .slotCount = {r.get('slotCount', 0)},\n")
            f.write(f"        .encounterRate = {r.get('encounterRate', 0)},\n")
            f.write(f"        .weightOffset = {r.get('weightOffset', 0)},\n")
            f.write(f"        .weightCount = {r.get('weightCount', 0)},\n")
            f.write(f"        .rareWeightOffset = {r.get('rareWeightOffset', 0)},\n")
            f.write(f"        .rareWeightCount = {r.get('rareWeightCount', 0)},\n")
            f.write(f"        .levelBandOffset = {r.get('levelBandOffset', 0)},\n")
            f.write(f"        .levelBandCount = {r.get('levelBandCount', 0)},\n")
            f.write(f"        .rareLevelBandOffset = {r.get('rareLevelBandOffset', 0)},\n")
            f.write(f"        .rareLevelBandCount = {r.get('rareLevelBandCount', 0)},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write(f"#define RANDOMIZER_AREA_RULE_COUNT {len(rules)}\n")
        f.write(f"#define RANDOMIZER_FISHING_RULE_COUNT {len(fishing_rules)}\n")
        f.write(f"#define RANDOMIZER_WEIGHT_POOL_COUNT {len(weight_pool)}\n")
        f.write(f"#define RANDOMIZER_RARE_WEIGHT_POOL_COUNT {len(rare_weight_pool)}\n")
        f.write(f"#define RANDOMIZER_LEVEL_BAND_POOL_COUNT {len(level_band_pool)}\n")
        f.write(f"#define RANDOMIZER_RARE_LEVEL_BAND_POOL_COUNT {len(rare_level_band_pool)}\n")

    # Exceptions (debug-only)
    if exceptions_data is not None:
        exc_list = load_exceptions(exceptions_data)
    else:
        exc_list = []
    exc_out.parent.mkdir(parents=True, exist_ok=True)
    with exc_out.open("w", encoding="utf-8") as fexc:
        fexc.write("// Auto-generated by build_randomizer_area_rules.py. Do not edit manually.\n")
        fexc.write("#pragma once\n")
        fexc.write("#include \"global.h\"\n")
        fexc.write("struct RandomizerException {\n")
        fexc.write("    u8 mapGroup;\n")
        fexc.write("    u8 mapNum;\n")
        fexc.write("    u8 areaMask;\n")
        fexc.write("    u8 timeSlot;\n")
        fexc.write("    u8 rodType; // 0xFF=any\n")
        fexc.write("};\n\n")
        if exc_list:
            fexc.write("static const struct RandomizerException sRandomizerExceptions[] = {\n")
            for e in exc_list:
                fexc.write("    { ")
                fexc.write(f".mapGroup = {e['mapGroup']}, .mapNum = {e['mapNum']}, .areaMask = {e['areaMask']}, .timeSlot = {e['timeSlot']}, .rodType = {e['rodType']} ")
                fexc.write("},\n")
            fexc.write("};\n")
        else:
            fexc.write("static const struct RandomizerException sRandomizerExceptions[] = {};\n")
        fexc.write(f"#define RANDOMIZER_EXCEPTION_COUNT {len(exc_list)}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
