#!/usr/bin/env python3
"""
Generate area-based randomizer tables from YAML.

Input: data/randomizer/area_rules.yml
Output: generated/randomizer_area_rules.h

Features:
- Kits (reusable species lists) with apply/remove per area/gift.
- Deduplication with removal taking precedence.
- Empty WL detection (treated as error).
- Sorted, unique species IDs.

Note: Makefile integration is step D; this script can be invoked manually.
"""

import sys
import pathlib
import argparse
import yaml

THIS_DIR = pathlib.Path(__file__).resolve().parent
ROOT = THIS_DIR.parent
DEFAULT_INPUT = ROOT / "data/randomizer/area_rules.yml"
DEFAULT_OUTPUT = ROOT / "generated/randomizer_area_rules.h"

HEADER_PREAMBLE = """\
// Auto-generated by build_randomizer_area_rules.py. Do not edit manually.
#pragma once
#include "global.h"
#include "constants/species.h"
#include "constants/maps.h"

struct RandomizerAreaRule {
    u8 mapGroup;
    u8 mapNum;
    u8 areaMask;
    const u16 *whitelist;
    const u16 *blacklist;
    u16 whitelistCount;
    u16 blacklistCount;
    u8 maxRerolls;
    bool8 allowLegendOverride;
};

"""


def parse_args():
    ap = argparse.ArgumentParser()
    ap.add_argument("--in", dest="inp", default=str(DEFAULT_INPUT))
    ap.add_argument("--out", dest="out", default=str(DEFAULT_OUTPUT))
    return ap.parse_args()


def load_yaml(path: pathlib.Path):
    with path.open("r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def resolve_mask(mask):
    # Accept string names for readability
    mask_map = {
        "Land": 1 << 0,
        "Water": 1 << 1,
        "Fish": 1 << 2,
        "Rock": 1 << 3,
        "Hidden": 1 << 4,
        "Gift": 1 << 5,
    }
    if isinstance(mask, int):
        return mask
    if isinstance(mask, str):
        if mask in mask_map:
            return mask_map[mask]
        # Allow multi-name comma-separated
        parts = [p.strip() for p in mask.split(",")]
        val = 0
        for p in parts:
            if p not in mask_map:
                raise ValueError(f"Unknown areaMask '{p}'")
            val |= mask_map[p]
        return val
    raise ValueError(f"Unsupported areaMask type: {mask}")


def dedup_apply_remove(apply_list, remove_list):
    wl = []
    seen = set()
    remove_set = set(remove_list or [])
    for s in apply_list or []:
        if s in remove_set:
            continue
        if s in seen:
            continue
        wl.append(s)
        seen.add(s)
    return wl, sorted(remove_set)


def render_array(name, entries):
    lines = [f"static const u16 {name}[] = {{"]
    for s in entries:
        lines.append(f"    {s},")
    lines.append("};\n")
    return "\n".join(lines)


def main():
    args = parse_args()
    inp = pathlib.Path(args.inp)
    out = pathlib.Path(args.out)
    data = load_yaml(inp)

    kits = data.get("kits", {})
    areas = data.get("areas", {})
    gifts = data.get("gifts", {})

    wl_pool = []
    bl_pool = []
    rules = []

    def process_entry(name, entry, is_gift=False):
        nonlocal wl_pool, bl_pool, rules
        key = entry["key"]
        mapGroup = key["mapGroup"]
        mapNum = key["mapNum"]
        areaMask = resolve_mask(key["areaMask"])

        apply = []
        for kit_name in entry.get("apply", []):
            if kit_name not in kits:
                raise ValueError(f"Unknown kit '{kit_name}' in {name}")
            apply.extend(kits[kit_name])
        remove = []
        for kit_name in entry.get("remove", []):
            if kit_name not in kits:
                raise ValueError(f"Unknown kit '{kit_name}' in {name}")
            remove.extend(kits[kit_name])

        wl, bl = dedup_apply_remove(apply, remove)

        if len(wl) == 0:
            raise ValueError(f"Whitelist is empty for entry '{name}' (mapGroup={mapGroup}, mapNum={mapNum})")

        wl_offset = len(wl_pool)
        bl_offset = len(bl_pool)
        wl_pool.extend(wl)
        bl_pool.extend(bl)

        rule = {
            "mapGroup": mapGroup,
            "mapNum": mapNum,
            "areaMask": areaMask,
            "wl_offset": wl_offset,
            "wl_count": len(wl),
            "bl_offset": bl_offset,
            "bl_count": len(bl),
            "maxRerolls": entry.get("maxRerolls", 6),
            "allowLegendOverride": 1 if entry.get("allowLegendOverride", False) else 0,
            "name": name,
        }
        rules.append(rule)

    for name, entry in areas.items():
        process_entry(name, entry, is_gift=False)
    for name, entry in gifts.items():
        process_entry(f"gift_{name}", entry, is_gift=True)

    # Sort rules by mapGroup/mapNum/areaMask for deterministic lookup
    rules.sort(key=lambda r: (str(r["mapGroup"]), str(r["mapNum"]), r["areaMask"]))

    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8") as f:
        f.write(HEADER_PREAMBLE)
        f.write(render_array("sRandomizerAreaWhitelistPool", wl_pool))
        f.write(render_array("sRandomizerAreaBlacklistPool", bl_pool))

        f.write("static const struct RandomizerAreaRule sRandomizerAreaRules[] = {\n")
        for r in rules:
            f.write("    {\n")
            f.write(f"        .mapGroup = {r['mapGroup']},\n")
            f.write(f"        .mapNum = {r['mapNum']},\n")
            f.write(f"        .areaMask = {r['areaMask']},\n")
            f.write(f"        .whitelist = &sRandomizerAreaWhitelistPool[{r['wl_offset']}],\n")
            f.write(f"        .blacklist = &sRandomizerAreaBlacklistPool[{r['bl_offset']}],\n")
            f.write(f"        .whitelistCount = {r['wl_count']},\n")
            f.write(f"        .blacklistCount = {r['bl_count']},\n")
            f.write(f"        .maxRerolls = {r['maxRerolls']},\n")
            f.write(f"        .allowLegendOverride = {r['allowLegendOverride']},\n")
            f.write("    },\n")
        f.write("};\n\n")
        f.write(f"#define RANDOMIZER_AREA_RULE_COUNT {len(rules)}\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
