#ifndef GUARD_BATTLE_BGM_H
#define GUARD_BATTLE_BGM_H

#include "global.h"

enum BattleBgmTarget
{
    BATTLE_BGM_TARGET_TRAINER,
    BATTLE_BGM_TARGET_WILD,
    BATTLE_BGM_TARGET_COUNT,
};

enum BattleBgmChoice
{
    BATTLE_BGM_CHOICE_DEFAULT,
    BATTLE_BGM_CHOICE_HOENN_WILD,
    BATTLE_BGM_CHOICE_KANTO_WILD,
    BATTLE_BGM_CHOICE_HOENN_TRAINER,
    BATTLE_BGM_CHOICE_KANTO_TRAINER,
    BATTLE_BGM_CHOICE_HOENN_GYM,
    BATTLE_BGM_CHOICE_KANTO_GYM,
    BATTLE_BGM_CHOICE_HOENN_CHAMPION,
    BATTLE_BGM_CHOICE_KANTO_CHAMPION,
    BATTLE_BGM_CHOICE_ELITE_FOUR,
    BATTLE_BGM_CHOICE_FRONTIER_BRAIN,
    BATTLE_BGM_CHOICE_RIVAL,
    BATTLE_BGM_CHOICE_AQUA_MAGMA,
    BATTLE_BGM_CHOICE_AQUA_MAGMA_LEADER,
    BATTLE_BGM_CHOICE_REGI,
    BATTLE_BGM_CHOICE_GROUDON_KYOGRE,
    BATTLE_BGM_CHOICE_RAYQUAZA,
    BATTLE_BGM_CHOICE_MEW,
    BATTLE_BGM_CHOICE_KANTO_LEGEND,
    BATTLE_BGM_CHOICE_MEWTWO,
    BATTLE_BGM_CHOICE_DEOXYS,
    BATTLE_BGM_CHOICE_LEGEND_BEAST,
    BATTLE_BGM_CHOICE_BW2_IRIS,
    BATTLE_BGM_CHOICE_BW_LEGEND,
    BATTLE_BGM_CHOICE_DP_WILD,
    BATTLE_BGM_CHOICE_DP_TRAINER,
    BATTLE_BGM_CHOICE_DP_GYM,
    BATTLE_BGM_CHOICE_DP_CHAMPION,
    BATTLE_BGM_CHOICE_DP_LEGEND,
    BATTLE_BGM_CHOICE_DP_ELITE_FOUR,
    BATTLE_BGM_CHOICE_DP_GALACTIC,
    BATTLE_BGM_CHOICE_DP_GALACTIC_COMMANDER,
    BATTLE_BGM_CHOICE_DP_CYRUS,
    BATTLE_BGM_CHOICE_DP_RIVAL,
    BATTLE_BGM_CHOICE_DP_UXIE_MESPRIT_AZELF,
    BATTLE_BGM_CHOICE_DP_DIALGA_PALKIA,
    BATTLE_BGM_CHOICE_DP_ARCEUS,
    BATTLE_BGM_CHOICE_PL_GIRATINA,
    BATTLE_BGM_CHOICE_PL_FRONTIER_BRAIN,
    BATTLE_BGM_CHOICE_PL_REGI,
    BATTLE_BGM_CHOICE_HGSS_WILD,
    BATTLE_BGM_CHOICE_HGSS_TRAINER,
    BATTLE_BGM_CHOICE_HGSS_GYM,
    BATTLE_BGM_CHOICE_HGSS_CHAMPION,
    BATTLE_BGM_CHOICE_HGSS_LUGIA,
    BATTLE_BGM_CHOICE_HGSS_HO_OH,
    BATTLE_BGM_CHOICE_HGSS_ROCKET,
    BATTLE_BGM_CHOICE_HGSS_RIVAL,
    BATTLE_BGM_CHOICE_HGSS_SUICUNE,
    BATTLE_BGM_CHOICE_HGSS_ENTEI,
    BATTLE_BGM_CHOICE_HGSS_RAIKOU,
    BATTLE_BGM_CHOICE_HGSS_WILD_KANTO,
    BATTLE_BGM_CHOICE_HGSS_TRAINER_KANTO,
    BATTLE_BGM_CHOICE_HGSS_GYM_KANTO,
    BATTLE_BGM_CHOICE_HGSS_FRONTIER_BRAIN,
    BATTLE_BGM_CHOICE_HGSS_KYOGRE_GROUDON,
    BATTLE_BGM_CHOICE_HGSS_ARCEUS,
    BATTLE_BGM_CHOICE_COUNT,
};

u8 GetBattleBgmChoice(u8 target);
void SetBattleBgmChoice(u8 target, u8 choice);
const u8 *GetBattleBgmTargetName(u8 target);
const u8 *GetBattleBgmChoiceName(u8 choice);
u16 GetBattleBgmChoicePreviewSong(u8 target, u8 choice);
u16 ApplyBattleBgmSelection(u16 songId);

#endif // GUARD_BATTLE_BGM_H
