# 1 "data/maps/Route999/scripts.pory"

# 2 "data/maps/Route999/scripts.pory"
Route999_MapScripts::
# 3 "data/maps/Route999/scripts.pory"
	.byte 0
# 4 "data/maps/Route999/scripts.pory"

# 5 "data/maps/Route999/scripts.pory"
Route999_EventScript_Route999Sign::
# 6 "data/maps/Route999/scripts.pory"
	msgbox Route999_Text_Route999Sign, MSGBOX_SIGN
# 7 "data/maps/Route999/scripts.pory"
	end
# 8 "data/maps/Route999/scripts.pory"

# 9 "data/maps/Route999/scripts.pory"
Route999_Text_Route999Sign:
# 10 "data/maps/Route999/scripts.pory"
	.string "ROUTE 99\n"
# 11 "data/maps/Route999/scripts.pory"
	.string "{LEFT_ARROW} ROUTE 999$"
